name: deploy-container

on:
  push:
    branches: -master
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: package/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses:
